# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

osx_image: xcode8.1

cache:
  directories:
    - /Users/travis/Library/Caches/Yarn

install:
  - brew install yarn
  - yarn cache dir
  - cd ReactNativeStoreViewExample && yarn install
  - cd ios && pod install --no-repo-update

script:
  - set -o pipefail && xcodebuild test -workspace ReactNativeStoreViewExample.xcworkspace -scheme ReactNativeStoreViewExample -destination 'platform=iOS Simulator,name=iPhone 6' -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty
