# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

osx_image: xcode8.3

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash && source ~/.bashrc
  - yarn cache clean
  - cd ReactNativeStoreViewExample && yarn install
  - cd ios && pod update && pod install
  - rm -rf ~/Library/Developer/Xcode/DerivedData ~/Library/Caches/com.apple.dt.Xcode

script:
  - set -o pipefail && xcodebuild test -workspace ReactNativeStoreViewExample.xcworkspace -scheme ReactNativeStoreViewExample -destination 'platform=iOS Simulator,name=iPhone 6' -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO | xcpretty
